dist: trusty

language: node_js

node_js:
  - '6'

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg --add-architecture i386; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y wine nsis; fi

install:
  - npm install
  - npm run dist

deploy:
  provider: releases
  api_key:
    secure: na5lF4n72kkw4JSUI7VdMhZjmahm9b9WHZddSeXcctsrtSfVQSWw1MUyOUIdr2S61LZDUFhDsNRQSkyznc+WorPdZLnGgZ+CNeGP3l+iLbVBLfGU8gjZDrsbSLz5QRUcvBowCXGpnrrhmg6HTeQ1QkLEf1L1zkMWEop257ysb2bBouroJs2ElUMcqxEBvotjRmFjqHyPABBlBtsmV+BVEWhM9WO5Y1uyDG9aZztDfrj0WDPDmPUjyb29hEPEsW62yZ7yopzosneAY7yE/eozj4XlwYTxXLMvhd1vlsuu+qnrHoH8K2HUUkFBZPWv5R3dB7clBa+n6TyVvqIn8+GEbZN0h8jdhCK4Pem5DxTP1EsT0EhHJlhJks2cuuaHPTcox5R3KR45flk5/X42t/dYbZTPdkGhoMrfCOJxtp1Y2P1VZ/2pR1V0tWVASTthK+4uWWTCftNwyC5VOtW0hnFELfT1mU7Nl+iCUaXYUc2sN7gjfDITW/Yp3hw7Rrj6mRpX9nLNBVfumaanuIPuzPuKZRoFn2hkFDC5s7fjxbPXr0vyVFybMvWKUds5WYSsezJrerCHDK2zgoBersIUj5VxGY+vjDMdfVisauvx6F+QemrIfZypSNDoiVs9yPBgtPoa76pHRGTvEsmoplkq6KikYBXvg4RW5JS5t72oiiJfOHA=
  file:
    - dist/*.zip
    - dist/*.dmg
    - dist/*.exe
    - dist/*.AppImage
  file_glob: true
  skip_cleanup: true
  on:
    all_branches: true
